"""Pydantic schema exports."""

from app.schemas.academic import (
    CourseCreate,
    CourseResponse,
    CourseUpdate,
    DepartmentCreate,
    DepartmentResponse,
    DepartmentUpdate,
    ProgramCreate,
    ProgramResponse,
    ProgramUpdate,
    SemesterResponse,
)
from app.schemas.assessment import (
    CLOCreate,
    CLOPLOMappingResponse,
    CLOPLOMatrixUpdate,
    CLOResponse,
    CLOUpdate,
    PLOCreate,
    PLOResponse,
    PLOUpdate,
    StudentCLOAchievementResponse,
)
from app.schemas.common import OrmBase, PaginatedResponse
from app.schemas.people import (
    CohortResponse,
    StudentCreate,
    StudentResponse,
    StudentUpdate,
    TeacherCreate,
    TeacherResponse,
    TeacherUpdate,
    TokenResponse,
    UserCreate,
    UserResponse,
    UserUpdate,
)
from app.schemas.teaching import (
    EnrollmentCreate,
    EnrollmentGradeUpdate,
    EnrollmentResponse,
    GradeComponentResponse,
    GradeComponentTypeCreate,
    GradeComponentUpsert,
    SectionCreate,
    SectionResponse,
    SectionUpdate,
)

__all__ = [
    "CLOCreate",
    "CLOPLOMappingResponse",
    "CLOPLOMatrixUpdate",
    "CLOResponse",
    "CLOUpdate",
    "CohortResponse",
    "CourseCreate",
    "CourseResponse",
    "CourseUpdate",
    "DepartmentCreate",
    "DepartmentResponse",
    "DepartmentUpdate",
    "EnrollmentCreate",
    "EnrollmentGradeUpdate",
    "EnrollmentResponse",
    "GradeComponentResponse",
    "GradeComponentTypeCreate",
    "GradeComponentUpsert",
    "OrmBase",
    "PLOCreate",
    "PLOResponse",
    "PLOUpdate",
    "PaginatedResponse",
    "ProgramCreate",
    "ProgramResponse",
    "ProgramUpdate",
    "SectionCreate",
    "SectionResponse",
    "SectionUpdate",
    "SemesterResponse",
    "StudentCLOAchievementResponse",
    "StudentCreate",
    "StudentResponse",
    "StudentUpdate",
    "TeacherCreate",
    "TeacherResponse",
    "TeacherUpdate",
    "TokenResponse",
    "UserCreate",
    "UserResponse",
    "UserUpdate",
]
