# Setup Ngrok public URL for EduInsight (H54)
# Usage:
#   $env:NGROK_AUTHTOKEN = "<token-from-dashboard.ngrok.com>"
#   .\scripts\setup-ngrok.ps1 -Production
#
# Or:
#   .\scripts\setup-ngrok.ps1 -Authtoken "<token>" -Production

param(
    [string]$Authtoken = $env:NGROK_AUTHTOKEN,
    [int]$Port = 3000,
    [switch]$SkipSmoke,
    [switch]$Production
)

$ErrorActionPreference = "Stop"
$Root = Split-Path $PSScriptRoot -Parent
$NgrokExe = Join-Path $Root "ngrok_dir\ngrok.exe"
$TokenFile = Join-Path $Root "ngrok_dir\.authtoken"

if (-not $Authtoken -and (Test-Path $TokenFile)) {
    $Authtoken = (Get-Content $TokenFile -Raw).Trim()
}

if (-not $Authtoken) {
    Write-Error "Missing authtoken. Set `$env:NGROK_AUTHTOKEN or pass -Authtoken."
}

function Stop-PortListener {
    param([int]$ListenPort)
    Get-NetTCPConnection -LocalPort $ListenPort -ErrorAction SilentlyContinue |
        Select-Object -ExpandProperty OwningProcess -Unique |
        ForEach-Object {
            if ($_ -and $_ -ne 0) {
                Stop-Process -Id $_ -Force -ErrorAction SilentlyContinue
            }
        }
}

function Start-ProductionFrontend {
    param([string]$FrontendDir, [int]$ListenPort)
    Write-Host "==> Building frontend (production)..."
    Push-Location $FrontendDir
    try {
        npm run build
        if ($LASTEXITCODE -ne 0) { throw "npm run build failed with exit code $LASTEXITCODE" }
    } finally {
        Pop-Location
    }

    Write-Host "==> Starting next start on port $ListenPort ..."
    $startArgs = @(
        "-NoExit",
        "-Command",
        "Set-Location '$FrontendDir'; `$env:BACKEND_URL='http://127.0.0.1:8000'; npm run start -- -p $ListenPort"
    )
    Start-Process powershell -ArgumentList $startArgs -WindowStyle Minimized

    $deadline = (Get-Date).AddSeconds(60)
    while ((Get-Date) -lt $deadline) {
        try {
            $probe = Invoke-WebRequest -Uri "http://127.0.0.1:$ListenPort" -TimeoutSec 3 -UseBasicParsing
            if ($probe.StatusCode -ge 200) { return }
        } catch {
            Start-Sleep -Seconds 2
        }
    }
    throw "Frontend did not become ready on port $ListenPort after production start."
}

if (-not (Test-Path $NgrokExe)) {
    Write-Error "Ngrok not found at $NgrokExe. Extract ngrok.exe into ngrok_dir/."
}

if ($Production) {
    Write-Host "==> Production mode: stopping dev server on port $Port ..."
    Stop-PortListener -ListenPort $Port
    Start-Sleep -Seconds 1
    $frontendDir = Join-Path $Root "frontend"
    Start-ProductionFrontend -FrontendDir $frontendDir -ListenPort $Port
}

Write-Host "==> Configuring ngrok authtoken..."
& $NgrokExe config add-authtoken $Authtoken | Out-Null

Write-Host "==> Stopping existing ngrok processes..."
Get-Process -Name "ngrok" -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 1

Write-Host "==> Starting tunnel to localhost:$Port ..."
Start-Process -FilePath $NgrokExe -ArgumentList "http", "$Port" -WorkingDirectory $Root -WindowStyle Minimized

$deadline = (Get-Date).AddSeconds(20)
$publicUrl = $null
while ((Get-Date) -lt $deadline) {
    try {
        $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 2
        $publicUrl = ($tunnels.tunnels | Where-Object { $_.public_url -like "https://*" } | Select-Object -First 1).public_url
        if ($publicUrl) { break }
    } catch {
        Start-Sleep -Milliseconds 500
    }
}

if (-not $publicUrl) {
    Write-Error "Could not read public URL from ngrok API (http://127.0.0.1:4040). Check ngrok dashboard for limits."
}

$hostName = ([Uri]$publicUrl).Host
Write-Host "==> Public URL: $publicUrl"
Write-Host "==> Hostname:   $hostName"

$frontendEnv = Join-Path $Root "frontend\.env.local"
@(
    "# Generated by scripts/setup-ngrok.ps1",
    "NGROK_DEV_ORIGIN=$hostName",
    "BACKEND_URL=http://127.0.0.1:8000"
) | Set-Content -Path $frontendEnv -Encoding utf8
Write-Host "==> Wrote $frontendEnv"

$demoDayFile = Join-Path $Root "docs\12-Evaluation\demo-day-phase1.md"
$updatedAt = Get-Date -Format "yyyy-MM-dd HH:mm"
$demoLines = @(
    "# Demo Day Phase 1 - Submission Copy",
    "",
    "> Updated: $updatedAt",
    "",
    "| Field | Value |",
    "|:------|:------|",
    "| Project | EduInsight - AI Learning Analytics |",
    "| MVP URL | $publicUrl |",
    "| Video | TBD (V35) |",
    "| Slide | TBD (V34) |",
    "| Thumbnail | TBD (V45) |"
)
New-Item -ItemType Directory -Force -Path (Split-Path $demoDayFile) | Out-Null
Set-Content -Path $demoDayFile -Value $demoLines -Encoding utf8
Write-Host "==> Wrote $demoDayFile"

if (-not $SkipSmoke) {
    Write-Host "==> Smoke test (local proxy)..."
    try {
        $local = Invoke-WebRequest -Uri "http://127.0.0.1:$Port/api/v1/health" -TimeoutSec 10 -UseBasicParsing
        Write-Host "    local /api/v1/health: $($local.StatusCode) $($local.Content)"
    } catch {
        Write-Warning "    local health failed - start frontend and backend first."
    }

    Write-Host "==> Smoke test (public ngrok)..."
    $headers = @{ "ngrok-skip-browser-warning" = "true" }
    try {
        $remote = Invoke-WebRequest -Uri "$publicUrl/api/v1/health" -Headers $headers -TimeoutSec 20 -UseBasicParsing
        Write-Host "    public /api/v1/health: $($remote.StatusCode) $($remote.Content)"
    } catch {
        Write-Warning "    public health failed: $($_.Exception.Message)"
        Write-Warning "    If 403: account limit or frontend not running on port $Port."
    }
}

Write-Host ""
Write-Host "Next steps:"
if ($Production) {
    Write-Host "  Frontend: production (next start) on port $Port"
} else {
    Write-Host "  1. Restart frontend (pick up .env.local): cd frontend; npm run dev"
}
Write-Host "  2. Broadcast URL to team: $publicUrl"
Write-Host "  3. Keep ngrok + frontend + backend running until submission."
Write-Host ""
Write-Host "Tip: -Production serves built assets (less ngrok bandwidth than dev/HMR)."
