"""add prerequisite_note to courses

Revision ID: 27b19e034656
Revises: c9e3f1a2b845
Create Date: 2026-06-15 03:05:03.470158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b19e034656'
down_revision: Union[str, None] = 'c9e3f1a2b845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_plos',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('plo_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plo_id'], ['plos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'plo_id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('prerequisite_note')

    op.drop_table('course_plos')
    # ### end Alembic commands ###
